[theme]
primaryColor = "#006400"
backgroundColor = "#f5f5f5"
secondaryBackgroundColor = "#ffffff"
textColor = "#333333"
font = "sans serif"

[theme.dark]
primaryColor = "#28a745"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
address = "0.0.0.0"
port = 8501

[browser]
gatherUsageStats = false
